# Site wide configuration

title: Drawing with Data
description: "An artist's journey into the world of data science"
logo: logo-square.png #120x120.gif
teaser: site-teaser-logo.png #400x250.gif
locale: en_US
# url: //mmistakes.github.io/skinny-bones-jekyll

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
paginate: 5

# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Tiffany Moeller
  web:
  email:
  twitter: tif_moe
  linkedin: tiffanymoeller1
  github: TifMoe
  bio: "Data scientist in Chicago - python enthusiast and painter"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus:
    ad-client:
    ad-slot:
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
